---
- hosts: webserver.avinash.com
  become: yes
  handlers:
    - import_tasks: handlers/main.yml

  vars_files:
    - main.yml





  gather_facts: yes
  tasks:
    
   
     - name: "installing bind"
       yum:
        pkg: bind
        state: installed

     - name: "setting the hostname"
       ansible.builtin.hostname:
         name: webserver.avinash.com
       register: shell_out


    
     - name: "copying the conf file"
       template:
          src: named.conf.j2
          dest: /etc/named.conf
          owner: root
          group: named
          mode: 0660
       notify: restart named


     - name: "making the names directory"
       file:
          path: /etc/named
          state: directory
          owner: root
          group: named
          mode: 0750


     - name: "Copy named conf local file"
       template:
           src: named.conf.local.j2
           dest: /etc/named/named.conf.local
           owner: root
           group: named
           mode: 0640
       notify: restart named

     

     - name: "Copy forward file"
       template:
           src: db.forward.j2
           dest: /etc/named/zones/db.{{ domain }}
           owner: root
           group: named
           mode: 0640
       notify: restart named


     - name: "Copy reverse file"
       template:
           src: db.reverse.j2
           dest: /etc/named/zones/db.{{ rev_domain }}
           owner: root
           group: named
           mode: 0640
       notify: restart named
